name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install
      - name: Install SQLite dependencies
        run: npm install sqlite3
      - name: Configure environment for SQLite
        run: |
          echo "DB_DIALECT=sqlite" >> $GITHUB_ENV
          echo "DB_STORAGE=:memory:" >> $GITHUB_ENV
      - name: Check coding style
        run: npm run lint
      - name: Run tests
        env:
          DB_DIALECT: ${{ env.DB_DIALECT }}
          DB_STORAGE: ${{ env.DB_STORAGE }}
        run: npm test
